Repository wecode-bootcamp-korea/39-2nd-Wemong-frontend, pull requests merged in 2022-12, with the labels that each got.

#7 [39기 홍석현]MODIFY:카카오 소셜 로그인 버그 수정
  .gitignore
  package-lock.json
  package.json
  public/images/kakaologin.png
  src/Router.js
  src/components/Footer/Footer.js
  src/components/Nav/Nav.js
  src/pages/LoginPage/Kakao.js
  src/pages/LoginPage/KakaoLogin.js
  src/pages/LoginPage/LoginPage.js
  src/pages/MainPage/MainPage.js
  src/styles/GlobalStyle.js
Labels: 멘토 리뷰 요청

#2 [39기 이상윤] ADD: 예약 패이지 레이아웃 구현 완료
  package-lock.json
  package.json
  public/index.html
  src/Router.js
  src/pages/ReservationPage/ReservationPage.js
  src/styles/theme.js
Labels: 멘토 리뷰 요청, 완료

#5 [39기 윤수민] ADD : DitailPage레이아웃 리뷰반영 레이아웃 머지 요청드립니다!
  package-lock.json
  package.json
  public/data/userInfoData.json
  public/images/입시 상담.PNG
  public/images/환불규정.PNG
  public/index.html
  src/pages/DetailPage/DetailPage.js
  src/pages/DetailPage/component/Calendar.js
  src/pages/DetailPage/component/CimmentBox.js
  src/pages/DetailPage/component/DitailLecture.js
  src/pages/DetailPage/component/NoComment.js
  src/pages/DetailPage/component/Review.js
  src/pages/DetailPage/component/ReviewComment.js
  src/pages/DetailPage/component/TutorInformation.js
Labels: 멘토 리뷰 요청

#11 [39기 홍석현]ADD:Feature/footer
  package-lock.json
  public/images/man.png
  public/images/man1.png
  public/images/man2.png
  public/images/man3.png
  public/images/man4.png
  public/images/man5.png
  src/Router.js
  src/components/Footer/Footer.js
  src/components/Footer/footerList.js
  src/components/Footer/footerMember.js
  src/pages/LoginPage/LoginPage.js
Labels: 멘토 리뷰 요청

#4 [39기 이상윤] ADD: 예약 내역 페이지 레이아웃 완성
  package-lock.json
  src/Router.js
  src/pages/OrderListPage/OrderListPage.js
Labels: 멘토 리뷰 요청

#8 [39기 이상윤] FIX: 에러 중복 작성 에러 수정
  package-lock.json
  src/Router.js
Labels: 멘토 리뷰 요청

#10 [39기 이상윤] 예약 페이지의 '토스 페이먼츠' 결제 기능 구현
  .gitignore
  package-lock.json
  package.json
  public/data/reservationData.json
  src/pages/ReservationPage/Calendar.js
  src/pages/ReservationPage/ReservationPage.js
  src/pages/ReservationPage/ReservationSuccess.js
Labels: 멘토 리뷰 요청

#14 [39기 홍석현]modify: conflict 해결
  src/Router.js
  src/components/Carousel.js
  src/pages/DetailPage/DetailPage.js
  src/pages/LoginPage/KakaoLogin.js
Labels: 멘토 리뷰 요청

#17 [39기 김호준] ADD:컨플릭트 해결
  package-lock.json
  package.json
  src/Router.js
  src/components/Carousel.js
  src/components/Nav/Nav.js
  src/components/Nav/NavList.js
  src/pages/MainPage/LectureList.js
  src/pages/MainPage/MainPage.js
Labels: 완료
